sources:
    - Sono.glyphs
axisOrder:
    - MONO
    - wght
familyName: "Sono"
stat:
  - name: Monospace
    tag: MONO
    values:
    - name: Proportional
      value: 0
    - name: Monospace
      value: 1
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
